const studentsData = [
  {
    name: "Evelyn",
    checked: true,
    assignment: "SCRUM",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W1D1-1",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W1D2-1",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W1D2-2",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W1D2-3",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W1D2-4",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W1D2-5",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W1D3-1",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W1D3-2",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W1D3-4",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W1D3-5",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: 5,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W1D4-1",
    difficulty: 4,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W1D5 - Project - Galgje",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W2D1-1",
    difficulty: 1,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W2D1-2",
    difficulty: 2,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W2D2-1",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W2D2-2",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W2D2-3",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W2D3-1",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W2D3-2",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W2D3-3",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W2D4-1",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W2D4-2",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W2D4-3",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W3D1-1",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W3D1-2",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W3D1-3",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W3D1-4",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W3D2-1",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W3D2-2",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W3D2-3",
    difficulty: 3,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W3D3-1",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W3D3-2",
    difficulty: 4,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W3D3-3",
    difficulty: 3,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W3D3-4",
    difficulty: 4,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W3D4-1",
    difficulty: 5,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W3D4-2",
    difficulty: 1,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W3D5 - Project - Todo-List",
    difficulty: 2,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W4D2-1",
    difficulty: 1,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W4D2-2",
    difficulty: 1,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W4D2-3",
    difficulty: 1,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W4D2-4",
    difficulty: 1,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W4D3-1",
    difficulty: 1,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W4D3-2",
    difficulty: 1,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W4D3-3",
    difficulty: 1,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W4D3-4",
    difficulty: 1,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W4D3-5",
    difficulty: 1,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: 1,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W5D4-1",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W6D1-1",
    difficulty: 5,
    funFactor: 5,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W6D2-1",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Evelyn",
    checked: true,
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: 5,
    funFactor: 5,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "SCRUM",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W1D1-1",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W1D2-1",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W1D2-2",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W1D2-3",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W1D2-4",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W1D2-5",
    difficulty: 4,
    funFactor: 2,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W1D3-1",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W1D3-2",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W1D3-4",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W1D3-5",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W1D4-1",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W1D5 - Project - Galgje",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W2D1-1",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W2D1-2",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W2D2-1",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W2D2-2",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W2D2-3",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W2D3-1",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W2D3-2",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W2D3-3",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W2D4-1",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W2D4-2",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W2D4-3",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W3D1-1",
    difficulty: 4,
    funFactor: 2,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W3D1-2",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W3D1-3",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W3D1-4",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W3D2-1",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W3D2-2",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W3D2-3",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W3D3-1",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W3D3-2",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W3D3-3",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W3D3-4",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W3D4-1",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W3D4-2",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W3D5 - Project - Todo-List",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W4D2-1",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W4D2-2",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W4D2-3",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W4D2-4",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W4D3-1",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W4D3-2",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W4D3-3",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W4D3-4",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W4D3-5",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W5D4-1",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W6D1-1",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W6D2-1",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Aranka",
    checked: true,
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "SCRUM",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W1D1-1",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W1D2-1",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W1D2-2",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W1D2-3",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W1D2-4",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W1D2-5",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W1D3-1",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W1D3-2",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W1D3-4",
    difficulty: 4,
    funFactor: 2,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W1D3-5",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W1D4-1",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W1D5 - Project - Galgje",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W2D1-1",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W2D1-2",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W2D2-1",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W2D2-2",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W2D2-3",
    difficulty: 4,
    funFactor: 2,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W2D3-1",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W2D3-2",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W2D3-3",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W2D4-1",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W2D4-2",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W2D4-3",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W3D1-1",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W3D1-2",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W3D1-3",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W3D1-4",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W3D2-1",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W3D2-2",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W3D2-3",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W3D3-1",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W3D3-2",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W3D3-3",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W3D3-4",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W3D4-1",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W3D4-2",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W3D5 - Project - Todo-List",
    difficulty: 4,
    funFactor: 2,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W4D2-1",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W4D2-2",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W4D2-3",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W4D2-4",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W4D3-1",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W4D3-2",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W4D3-3",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W4D3-4",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W4D3-5",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W5D4-1",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W6D1-1",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W6D2-1",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Floris",
    checked: true,
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "SCRUM",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W1D1-1",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W1D2-1",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W1D2-2",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W1D2-3",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W1D2-4",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W1D2-5",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W1D3-1",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W1D3-2",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W1D3-4",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W1D3-5",
    difficulty: 4,
    funFactor: 2,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W1D4-1",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W1D5 - Project - Galgje",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W2D1-1",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W2D1-2",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W2D2-1",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W2D2-2",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W2D2-3",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W2D3-1",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W2D3-2",
    difficulty: 4,
    funFactor: 2,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W2D3-3",
    difficulty: 4,
    funFactor: 2,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W2D4-1",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W2D4-2",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W2D4-3",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W3D1-1",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W3D1-2",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W3D1-3",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W3D1-4",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W3D2-1",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W3D2-2",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W3D2-3",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W3D3-1",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W3D3-2",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W3D3-3",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W3D3-4",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W3D4-1",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W3D4-2",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W3D5 - Project - Todo-List",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W4D2-1",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W4D2-2",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W4D2-3",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W4D2-4",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W4D3-1",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W4D3-2",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W4D3-3",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W4D3-4",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W4D3-5",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W5D4-1",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W6D1-1",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W6D2-1",
    difficulty: 4,
    funFactor: 2,
  },
  {
    name: "Hector",
    checked: true,
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "SCRUM",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W1D1-1",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W1D2-1",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W1D2-2",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W1D2-3",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W1D2-4",
    difficulty: 4,
    funFactor: 2,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W1D2-5",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W1D3-1",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W1D3-2",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W1D3-4",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W1D3-5",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W1D4-1",
    difficulty: 4,
    funFactor: 2,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W1D5 - Project - Galgje",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W2D1-1",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W2D1-2",
    difficulty: 4,
    funFactor: 2,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W2D2-1",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W2D2-2",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W2D2-3",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W2D3-1",
    difficulty: 4,
    funFactor: 2,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W2D3-2",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W2D3-3",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W2D4-1",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W2D4-2",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W2D4-3",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W3D1-1",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W3D1-2",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W3D1-3",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W3D1-4",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W3D2-1",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W3D2-2",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W3D2-3",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W3D3-1",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W3D3-2",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W3D3-3",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W3D3-4",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W3D4-1",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W3D4-2",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W3D5 - Project - Todo-List",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W4D2-1",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W4D2-2",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W4D2-3",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W4D2-4",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W4D3-1",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W4D3-2",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W4D3-3",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W4D3-4",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W4D3-5",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W5D4-1",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W6D1-1",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W6D2-1",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Martina",
    checked: true,
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "SCRUM",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W1D1-1",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W1D2-1",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W1D2-2",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W1D2-3",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W1D2-4",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W1D2-5",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W1D3-1",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W1D3-2",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W1D3-4",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W1D3-5",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W1D4-1",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W1D5 - Project - Galgje",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W2D1-1",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W2D1-2",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W2D2-1",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W2D2-2",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W2D2-3",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W2D3-1",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W2D3-2",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W2D3-3",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W2D4-1",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W2D4-2",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W2D4-3",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W3D1-1",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W3D1-2",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W3D1-3",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W3D1-4",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W3D2-1",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W3D2-2",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W3D2-3",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W3D3-1",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W3D3-2",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W3D3-3",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W3D3-4",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W3D4-1",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W3D4-2",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W3D5 - Project - Todo-List",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W4D2-1",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W4D2-2",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W4D2-3",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W4D2-4",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W4D3-1",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W4D3-2",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W4D3-3",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W4D3-4",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W4D3-5",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W5D4-1",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: 4,
    funFactor: 2,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W6D1-1",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W6D2-1",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Maurits",
    checked: true,
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "SCRUM",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W1D1-1",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W1D2-1",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W1D2-2",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W1D2-3",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W1D2-4",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W1D2-5",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W1D3-1",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W1D3-2",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W1D3-4",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W1D3-5",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W1D4-1",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W1D5 - Project - Galgje",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W2D1-1",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W2D1-2",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W2D2-1",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W2D2-2",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W2D2-3",
    difficulty: 4,
    funFactor: 2,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W2D3-1",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W2D3-2",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W2D3-3",
    difficulty: 4,
    funFactor: 2,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W2D4-1",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W2D4-2",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W2D4-3",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W3D1-1",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W3D1-2",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W3D1-3",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W3D1-4",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W3D2-1",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W3D2-2",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W3D2-3",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W3D3-1",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W3D3-2",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W3D3-3",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W3D3-4",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W3D4-1",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W3D4-2",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W3D5 - Project - Todo-List",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W4D2-1",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W4D2-2",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W4D2-3",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W4D2-4",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W4D3-1",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W4D3-2",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W4D3-3",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W4D3-4",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W4D3-5",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W5D4-1",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W6D1-1",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W6D2-1",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Rahima",
    checked: true,
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "SCRUM",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W1D1-1",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W1D2-1",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W1D2-2",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W1D2-3",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W1D2-4",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W1D2-5",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W1D3-1",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W1D3-2",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W1D3-4",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W1D3-5",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W1D4-1",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W1D5 - Project - Galgje",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W2D1-1",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W2D1-2",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W2D2-1",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W2D2-2",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W2D2-3",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W2D3-1",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W2D3-2",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W2D3-3",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W2D4-1",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W2D4-2",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W2D4-3",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W3D1-1",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W3D1-2",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W3D1-3",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W3D1-4",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W3D2-1",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W3D2-2",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W3D2-3",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W3D3-1",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W3D3-2",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W3D3-3",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W3D3-4",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W3D4-1",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W3D4-2",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W3D5 - Project - Todo-List",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W4D2-1",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W4D2-2",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W4D2-3",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W4D2-4",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W4D3-1",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W4D3-2",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W4D3-3",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W4D3-4",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W4D3-5",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W5D4-1",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W6D1-1",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W6D2-1",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Sandra",
    checked: true,
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "SCRUM",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W1D1-1",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W1D2-1",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W1D2-2",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W1D2-3",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W1D2-4",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W1D2-5",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W1D3-1",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W1D3-2",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W1D3-4",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W1D3-5",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W1D4-1",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W1D5 - Project - Galgje",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W2D1-1",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W2D1-2",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W2D2-1",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W2D2-2",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W2D2-3",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W2D3-1",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W2D3-2",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W2D3-3",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W2D4-1",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W2D4-2",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W2D4-3",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W3D1-1",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W3D1-2",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W3D1-3",
    difficulty: 4,
    funFactor: 2,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W3D1-4",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W3D2-1",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W3D2-2",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W3D2-3",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W3D3-1",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W3D3-2",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W3D3-3",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W3D3-4",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W3D4-1",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W3D4-2",
    difficulty: 4,
    funFactor: 2,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W3D5 - Project - Todo-List",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W4D2-1",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W4D2-2",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W4D2-3",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W4D2-4",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W4D3-1",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W4D3-2",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W4D3-3",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W4D3-4",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W4D3-5",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: 4,
    funFactor: 2,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W5D4-1",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: 4,
    funFactor: 2,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W6D1-1",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W6D2-1",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Wietske",
    checked: true,
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "SCRUM",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W1D1-1",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W1D2-1",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W1D2-2",
    difficulty: 1,
    funFactor: 3,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W1D2-3",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W1D2-4",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W1D2-5",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W1D3-1",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W1D3-2",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W1D3-4",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W1D3-5",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W1D4-1",
    difficulty: 4,
    funFactor: 2,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W1D5 - Project - Galgje",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W2D1-1",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W2D1-2",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W2D2-1",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W2D2-2",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W2D2-3",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W2D3-1",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W2D3-2",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W2D3-3",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W2D4-1",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W2D4-2",
    difficulty: 4,
    funFactor: 3,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W2D4-3",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W3D1-1",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W3D1-2",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W3D1-3",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W3D1-4",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W3D2-1",
    difficulty: 1,
    funFactor: 4,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W3D2-2",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W3D2-3",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W3D3-1",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W3D3-2",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W3D3-3",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W3D3-4",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W3D4-1",
    difficulty: 2,
    funFactor: 4,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W3D4-2",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W3D5 - Project - Todo-List",
    difficulty: 3,
    funFactor: 2,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W4D2-1",
    difficulty: 2,
    funFactor: 1,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W4D2-2",
    difficulty: 3,
    funFactor: 3,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W4D2-3",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W4D2-4",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W4D3-1",
    difficulty: 3,
    funFactor: 4,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W4D3-2",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W4D3-3",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W4D3-4",
    difficulty: 3,
    funFactor: 1,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W4D3-5",
    difficulty: 2,
    funFactor: 3,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: 4,
    funFactor: 1,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W5D4-1",
    difficulty: 2,
    funFactor: 2,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: 1,
    funFactor: 2,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W6D1-1",
    difficulty: 4,
    funFactor: 4,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W6D2-1",
    difficulty: 1,
    funFactor: 1,
  },
  {
    name: "Storm",
    checked: true,
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: 3,
    funFactor: 3,
  },
];

export default studentsData;
